### ISSUE TITLE
Add Text Input for DNA

### ISSUE THREAD

**Issue by cjmiller1622** [bioneos/training-plan#2]
**User Input**
Read in a user input for a DNA sequence. Be sure to verify that the sequence is a valid DNA sequence (only containing appropriate bases A, C, G, T). This sequence will later be used to transcribe and translate a protein sequence.

**Comment by cjmiller1622** [comment]
User can only type in DNA sequence.

**Comment by Wheelspawn** [comment]
Right now the user cannot choose to upload .fasta as nucleotide or protein sequence. It uploads to the protein field by default.
